### PR TITLE
Documentation update pass

### PR DESCRIPTION
**Pull request by dshemetov**
Part of #13.

Testing the API endpoints:
- each endpoint has a link to the API docs
- most endpoints have an example call that works

Endpoints tested:
- [x] afhsb
- [x] cdc
- [x] covid_hosp_facility_lookup
- [x] covid_hosp_facility
- [x] covid_hosp_state_timeseries
- [x] covidcast_meta
- [x] ~~covidcast_nowcast~~ (not an active endpoint yet)
- [x] covidcast
- [x] delphi
- [ ] dengue_nowcast (need valid locations, but API is lacking)
- [ ] dengue_sensors (need valid locations and names, but API is lacking)
- [ ] ecdc_ili
- [x] flusurv
- [x] fluview_clinical
- [x] fluview_meta
- [x] fluview
- [x] gft
- [x] ght
- [ ] kcdc_ili (need valid region, but API is lacking)
- [x] meta_afhsb
- [x] meta_norostat
- [x] meta
- [x] nidss_dengue
- [x] nidss_flu
- [x] norostat
- [x] nowcast
- [ ] paho_dengue (bug prevents testing)
- [x] quidel
- [x] sensors
- [x] twitter
- [x] wiki

### CODE REVIEW

**Comment by brookslogan** [comment]
Note this will need a re-`document()` when ready.  (From the checklist, it looks pretty ready; can the remaining boxes be left for another issue?)

**Review by dajmcdon — APPROVED** [review]

**Comment by brookslogan** [comment]
This still needs a re-`document()`.  And an issue to address the remaining checklist items.

**Comment by brookslogan** [comment]
Closes #50.

**Comment by brookslogan** [comment]
Looks like
- the first CI run with the updated documentation timed out trying to test the examples
- locally a `check()` runs fine on my system
- locally a `devtools::run_examples()` is currently stuck at the `covid_hosp_facility_lookup` example; not sure if it's going to terminate or not.

Some potential causes:
- an API hiccup
- a GitHub Action configuration issue
- a bug in the examples

**Review by brookslogan — COMMENTED** [review]
Not sure how I self-requested review.  The doc changes looked good when I looked them over before.  The re-`document()` revealed an (inconsistent) issue with examples taking a long time / never terminating, maybe due to sometimes-long `covid_hosp_facility_lookup` run times; I'm following up on this on Slack.  I think it's good to either merge or to wait for some findings regarding what's causing the inconsistent long run times.  @keanmingtan would it slow you down at all to continue development off a branch split off from this PR's branch?

**Comment by brookslogan** [comment]
Trying out just marking this + another long-running example `\donttest`.  CI checks are [still going to run them](https://github.com/r-lib/devtools/issues/2216), so if it's this causing them to time out, we may need to change this to something even more restrictive until the `covid_hosp_facility_lookup` backend performance improvements and a https://github.com/cmu-delphi/delphi-epidata/issues/48 fix are out.

**Pull request merged**
