### PR TITLE
fix: actual license details

### PR DESCRIPTION
**Pull request by dsweber2**
Following R conventions on the owners, as its ambiguous which orgs exactly would hold. Also adding the particular rights claimed...

### CODE REVIEW

**Review by brookslogan — APPROVED** [review]
Diffs look right.  Any idea why macos check is failing?  Is that a preexisting or intermittent thing?

**Comment by dsweber2** [comment]
```
   Error: 
  ! error in pak subprocess
  Caused by error in `file(con, "rb")`:
  ! cannot open the connection
```
:thinking: not sure this is an us problem... I don't remember it happening before

**Review by dshemetov — COMMENTED** [review]
Why are there two license files (probably R pkgdown needs the Markdown?). Why are they different?

**Comment by dsweber2** [comment]
It's what `usethis::use_mit_license()` generates, for whatever reason, so I just went with that

**Pull request merged**
